workflows:
  flutter-apk-build:
    name: Flutter APK Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Fetch dependencies
        script: |
          flutter pub get

      - name: Build Android Release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
